### ISSUE TITLE
review list of properties for find_trees and find_studies

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/otindex#31]
[Draft documentation](https://github.com/OpenTreeOfLife/otindex/wiki/Otindex-and-Oti-differences#properties) of searchable properties for trees and studies in otindex.

Review requested. @jar398 @jimallman @josephwb

**Comment by josephwb** [comment]
Is there a timeframe on this?

**Comment by kcranston** [comment]
Within the next week would be good. Should have the NeXSON changes for preferred trees / ot:candidateTreeForSynthesis worked out by then and ready to implement.

**Comment by josephwb** [comment]
I'm not sure how to review: the math on the new vs. deprecated properties does not seem to add up (e.g. the page mentions 53 study properties, but running the script reports only 51; page says 32 tree properties, but script says 28).

Can all of the new vs. old properties be posted on that page rather than running a script? Presumably we might want to consider deprecating more?

**Comment by josephwb** [comment]
Is this repo not hooked up to gitter yet? Should do that so other people can note issues, etc.

**Comment by josephwb** [comment]
It would be nice on that page to list the property _types_ as well.

**Comment by kcranston** [comment]
Ok, made the following changes:

* added otindex to the gitter integrations
* put the full result of the API call in the doc (and removed the link to the peyotl script, because that was confusing)
* included links to NexSON / NeXML docs that have full descriptions of the properties that aren't specific to otindex

**Comment by josephwb** [comment]
Thanks!

**Comment by kcranston** [comment]
Assuming that there aren't any concerns, given lack of comment. Closing.

**Comment by jar398** [comment]
Since the focal clade is found using the TNRS, it seems a lost opportunity
for the curator app to fail to put the OTT id in the study (
ot:focalCladeOTTId).​  Minor thing.

**Comment by kcranston** [comment]
> Since the focal clade is found using the TNRS, it seems a lost opportunity for the curator app to fail to put the OTT id in the study ( ot:focalCladeOTTId).​ Minor thing.

Not relevant for otindex. I suggest moving the request to opentree repo if you want this addressed. If the property exists in the NeXSON, otindex will return it.
