### ISSUE TITLE
Indent json response?

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/otindex#34]
If for nothing else that it is consistent with treemachine, taxomachine, propinquity.
e.g. counting occurrences of words with `grep` + `wc`.

**Comment by mtholder** [comment]
seems like this should be a client side operation. I don't think we should try to guarantee the details of the text -> JSON mapping other than the encoding.

**Comment by josephwb** [comment]
I get that. But it is easy to do, so are there any reasons to _not_ do it?

**Comment by josephwb** [comment]
I guess I will just go ahead and make this a feature request. Seems easy to do, cannot break anything downstream, and saves a bit of typing for people doing routine grepping.

**Comment by josephwb** [comment]
Pinging @kcranston. I'd like to see this feature, and I cannot see how it might break anything.

**Comment by jar398** [comment]
"no reason not to do x" and "won't break anything" are not sufficient
reasons to add unnecessary complexity, documentation burden, testing
burden, etc.​ The threshold is higher than that.

We could put something like the following in the documentation:

    import sys, json
    json.dump(json.load(sys.stdin), sys.stdout, indent=2)

**Comment by josephwb** [comment]
How about consistency: all other jsons (at least the that I use: taxomachine, treemachine, propinquity, oti) are formatted like this? How about it is more human readable? How about it is an innocuous feature request from a user?

Adding stuff to the already dense documentation is a possibility, but why not make things easier for users? Especially if we would like to engage new users.

**Comment by josephwb** [comment]
Don't know why this is closed. @kcranston seemed to think it was fine (but not a priority).

**Comment by josephwb** [comment]
Note that the current problem (incomplete study record) with otindex was identified from the formatted json.

**Comment by mtholder** [comment]
Locking this for the same reason I closed it: DFTT
