### ISSUE TITLE
add / update trees not updating json 'data' field

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/otindex#43]
The add / update study code is not updating the jsonb `data` field in the study table. Code is [here](https://github.com/OpenTreeOfLife/otindex/blob/master/otindex/add_update_studies.py#L140).

**Comment by kcranston** [comment]
Ok, so the issue is that the GIN index on the jsonb `data` column is not being updated after the UPDATE to the table. Investigating.

**Comment by snacktavish** [comment]
ah! So I guess we did know about this :P fixed in https://github.com/OpenTreeOfLife/otindex/commit/77d25a917079d207dda39c0a28869175e61edc30
