### ISSUE TITLE
Tree additions

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/otindex#58]
https://github.com/OpenTreeOfLife/opentree/issues/1301

Tree additions not updating, for some reason. Web-hook from github to phylesystem-api to nudge index times out, although other pushes are succeeding.

**Comment by snacktavish** [comment]
Should be fixed by new webhook... although lack of specific example makes it hard to assess.

**Comment by jimallman** [comment]
Thanks @snacktavish ! I'll re-route the new webhook-creation code (Ansible) to point to this URL.

**Comment by jimallman** [comment]
New webhook uses this URL. Marking as done (pending testing of cache-clearing behavior).
